Qt minimal working example
gmusya/data-structure-visualization pull request #1
Opened 2023-05-07 15:37 UTC by gmusya

Основная часть приложения готова

Плохо понимаю, как улучшить red_black_tree.h (хочется избавиться от erase на 200 строк; можно, конечно, все if'ы повыносить в функции и поназывать их "case #n", но этот вариант как-то не нравится)

2023-05-15 18:40 UTC, DimaTrushin requested changes
1) У тебя глобально не верная имплементация обзервера. Посмотри мои тексты, как это надо делать. Из-за этого у тебя кривая имплементация всех компонент MVC.
2) Ты везде работаешь с памятью через new. Никогда так не делай. Оборачивай в unique_ptr, если надо владеть ресурсом.
3) У Qt ресурсов есть владельцы, ты не всем компонентам устанавливаешь владельцев, потому у тебя идут утечки. Лучше всего выделение памяти под Qt ресурсы прятать куда-то вдали от пользователя кода.
4) Никогда не пользуйся shared_ptr на неконстантные объекты.
5) Ты не отключил exception в cmake. Более того, ты в одном из мест перехватываешь исключения. А это значит, тебе надо предусматривать их обработку везде. По-хорошему Qt-event loop их не поддерживает и не является exception safe. Все exception надо перехватывать до выхода в него. Надо обязательно заворачивать все в RAII. Нельзя пользоваться new и delete явно. Нельзя выделять более одного ресурса в конструкторе и удалять более одного в деструкторе.

2023-05-15 18:40 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Добавь
set(CXX_STANDARD_REQUIRED ON)

2023-05-15 18:40 UTC, DimaTrushin commented on CMakeLists.txt
> +# add_link_options(-fsanitize=address)
Это компиляторо зависимые флаги. Таких нет под msvc. Потому сделай тут проверку компилятора и установи эти флаги только для своего. Это gcc?

2023-05-15 18:40 UTC, DimaTrushin commented on CMakeLists.txt
> +# set(CMAKE_CXX_FLAGS "-Os -DNDEBUG -Wall -Wextra")
Почему не через add_compiler_options? Плюс эта хрень компиляторо зависимая.

2023-05-15 18:40 UTC, DimaTrushin commented on CMakeLists.txt
> +target_link_libraries(test_performance gtest gtest_main)
Кирпичи в конце файлов убери.

2023-05-15 18:40 UTC, DimaTrushin commented on CMakeLists.txt
> +# set(CMAKE_CXX_FLAGS "-O3 -Wall -Wextra")
Если хочешь настраиваемые флаги, то лучше сделай макрос включаемым или настраиваемым. И потом в зависимости от этого подключай все. То есть чтобы включить что-то или отключить, достаточно добавить макрос в команду компиляции, а не бегать по  cmake файлу и искать, где что перекомментировать.

2023-05-15 18:40 UTC, DimaTrushin commented on README.md
Если у тебя код под конкретный компилятор, то это стоит указать.

2023-05-15 18:40 UTC, DimaTrushin commented on main.cpp
> +    Application::Run();
Странно, что цикл запускает не q_app.exec(). Потому что именно эта функция заставляет запуститься event loop в Qt экосистеме.

2023-05-15 18:40 UTC, DimaTrushin commented on application.h
> +class Application {
Не пиши классы в глобальном namespace. Объект Application тоже надо заворачивать.

2023-05-15 18:40 UTC, DimaTrushin commented on application.h
> +    DSVisualization::Model* model_ptr;
Какого хера?
1) Если тебе нужен указатель, который владеет данными, то используй unique_ptr.
2) Но в данном случае можно использовать просто переменную член класса. Дело в том, что если тебе надо адрессовать этот объект внутри Application, то ты всегда это можешь сделать, пока жив Application. А чтобы гарантировать, что объект не переедет, надо просто удалить 4 метода по копированию и перемещению Application. И тогда не надо возиться с памятью.

2023-05-15 18:40 UTC, DimaTrushin commented on application.cpp
> +    model_ptr = new DSVisualization::Model();
Если тут будет брошено исключение, то вся память потечет. Плюс ты не пользуешься RAII. Плюс ты нарушаешь правила ответственности объектов. Application не должен заниматься менеджментом ресурсов переменной, она сама должна этим заниматься. В кайнем случае сделай unique_ptr, но вообще хорошо бы сделать просто переменную.
Если цель -- освободить стек, то надо сделать ApplicationImpl, пересадить все туда, а потом в Application сделать unique_ptr на ApplicationImpl.

2023-05-15 18:40 UTC, DimaTrushin commented on application.cpp
> +    view_ptr->SubscribeFromController(controller_ptr->GetObserver());
плохое название метода. SubscribeToData. Ты подписываешься на что-то, а не от кого-то.

2023-05-15 18:40 UTC, DimaTrushin commented on application.cpp
> +    view_ptr->UnsubscribeFromController(controller_ptr->GetObserver());
Протокол observer/observable не требует отписывания. Он должен сам отписать все объекты при разрушении. Это лишняя работа. Этого быть не должно, если observer/observable написан правильно.

2023-05-15 18:40 UTC, DimaTrushin commented on application.cpp
> +    delete controller_ptr;
Этого тоже быть не должно, если есть RAII.

2023-05-15 18:40 UTC, DimaTrushin commented on application.cpp
> +int Application::Run() {
Хорошо, я думаю, я понял, что ты сделал. Ты перетащил логику event loop-а из QApplication сюда. То есть ты как бы считаешь, что Application это и есть объект управляющий всей экосистемой на thread-е. Технически это не правда. Я предпочитаю думать так.
QApplication -- это объект отвечающий за работу Qt экосистемы на main thread. А наше Application -- это просто один из обслуживаемых объектов в этой экосистеме. В частности ты можешь создать несколько таких разных Application у себя. Ну просто несколько глобальных окон со своими задачами. Это глупо, но так можно сделать и это так и устроено.
В целом я не вижу смысла эту функцию сюда выделять. А какая была идея за этим? Что еще сюда ты хотел добавить?

2023-05-15 18:40 UTC, DimaTrushin commented on model.h
> +    using ObservableModelViewPtr = std::shared_ptr<Observable<DataModelView>>;
Обмазать бы тебя говном тут. Я уже это делал с Сережей в видосе по избиению младенцев. Но видимо его никто не смотрел. Тебе никогда не нужны shared_ptr. Убрать.

2023-05-15 18:40 UTC, DimaTrushin commented on observer.h
> +        }
Моему отчаянию нет предела. Это делается не так
1) Сделай псевдоним
```cpp
using Action = std::function<void(const Data&)>;
```
2) Не используй this явно в методах класса.
3) Если делаешь x = tmp, где tmp временный или неиспользуемый далее локальный объект, делай из него move, например x = std::move(tmp)
4) Инициализировать поля надо в списке инициализации
```cpp
Observer(Action on_subscribe, Action on_notify, Action on_unsubscribe)
  : on_subscribe_(std::move(on_subscribe)),
    on_notify_(std::move(on_notify)),
    on_unsubscribe_(std::move(on_unsubscribe)) {}
```
5) Используй в названии переменных класса модификатор вроде _ в конце имени. Дело в том, что переменные класса являются глобальными для методов класса и их надо уметь отличать в методах класса от локальных переменных именно метода класса. Это касается именно C++, а не C кода.
6) Ключевое слово explicit тут бессмысленно. Оно имеет смысл только для конструктора с 1 аргументом.

2023-05-15 18:40 UTC, DimaTrushin commented on observer.h
> +        std::function<void(const Data& data)> on_unsubscribe;
1) Дефолтные значения надо сообщать тут
Action on_notify_ = do_nothing;
2) Поставь переменные тут в том порядке, в котором они принимаются в конструкторе. Потому что инициализируются они в том порядке в котором идут тут, а в списке инициализации их удобнее писать в том же порядке, что и аргументы.

2023-05-15 18:40 UTC, DimaTrushin commented on observer.h
> +        }
Эти методы должны быть доступны только observable, никто другой их не должен видеть.

2023-05-15 18:40 UTC, DimaTrushin commented on observer.h
У тебя отсутствует вся логика гарантии взаимодействия между observable и observer. Я же даже высылал текст, в котором написано, как надо имплементировать протокол взаимодействия.

2023-05-15 18:40 UTC, DimaTrushin commented on observable.h
> +        std::vector<std::shared_ptr<Observer<Data>>> observers;
Это ошибка дизайна. shared_ptr предполагает, что ты в ответе за хранение объекта. Observable не должна хранить observer-а. Предположим у тебя есть сервер сообщающий погоду и пользовательское приложение на телефоне его прослушивающее. Представь, что сервер в ответе за то, закрывается ли у пользователя приложение или нет. Это же трындец. Тут должны быть только сырые указатели. Задача у тебя лишь увидеть observer-а. А корректность указателя должна гарантироваться протоколом.

2023-05-15 18:40 UTC, DimaTrushin commented on observable.h
> +    public:
Проблема твоей имплементации в том, что у тебя observer не умеет оповещать о своей смерти и отписываться.

2023-05-15 18:40 UTC, DimaTrushin commented on observable.h
> +        void Subscribe(std::shared_ptr<Observer<Data>> observer, const Data& data) {
Это нарушение дизайна. Observable должна сама знать, откуда брать данные для оповещения. Иначе это все костыли и копыта.

2023-05-15 18:40 UTC, DimaTrushin commented on observable.h
Перечитай мой текст по имплементации.

2023-05-15 18:40 UTC, DimaTrushin commented on model.h
> +    using ObservableModelViewPtr = std::shared_ptr<Observable<DataModelView>>;
Помести все эти using-ги внутри  модели. Дело в том, что это псевдонимы только для данной модели, и они не должны из нее утекать. Кроме того, внутри этой модели ты можешь упростить все названия. Например вместо DataModelView ты можешь просто сказать Data. Потому что у модели данные только для View и к ним доступ будет по Model::Data. Появится иерархия и локальность.

2023-05-15 18:40 UTC, DimaTrushin commented on model.h
> +        void UnsubscribeFromView(ObserverModelViewPtr observer_model_view);
Этого метода быть не должно, отписка должна быть автоматом.

2023-05-15 18:40 UTC, DimaTrushin commented on model.h
> +        ~Model();
Зачем нужен деструктор, если у тебя нет ресурсов в классе, которые надо менеджерить? А если ты хочешь делать лог, то почему только в деструкторе и конструкторе? Есть же еще 4 автоматических метода вроде копирующего конструктора, копирующего присваивания, мув конструктора и мув присваивания.

2023-05-15 18:40 UTC, DimaTrushin commented on model.h
> +        RedBlackTree<int> values;
- Интересно, если модель это не дерево, то как ты будешь оповещать из середины методов дерева?
- И почему название values?

2023-05-15 18:40 UTC, DimaTrushin commented on model.h
> +        ObservableModelViewPtr observable_model_view;
Тут должно быть 
Observable<Data> port_;

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +#include <vector>
Повторение инклуда.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        using NodePtr = std::shared_ptr<Node>;
Плохая идея. Зачем тебе shared_ptr? Тебе же надо владеть узлом дерева в одном месте. Используй unique_ptr на детей и raw ptr на родителя. Первые два холдящие, последний просто указывающий.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            friend RedBlackTree<T>;
1) А разве у Node есть инварианты, чтобы делать его классом?
2) Если нет инвариантов, то это должна быть структура. Если есть инварианты, то данные не должны быть публичными.
3) Если это структура, то не надо друзей, все имеют доступ.

Убрать.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            NodePtr right;
Привет циклическая утечка память из джавы. У тебя узел холдит своих детей и каждый ребонок холдит своего родителя. В итоге у тебя цикл в зависимостях владения. Потому у тебя никогда такое дерево не разрушится.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            enum Color color;
лишнее enum

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            Node(const T& value1, NodePtr parent1, enum Color color1);
У структуры не должно быть деструкторов. У нее есть aggregate initialization. Никогда не делай конструкторы для структуры.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            NodePtr GetUncle();
Не делай геттеры для структуры.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            Kid WhichKid(NodePtr kid);
Не делай вперемешку static и non static методы. А то невозможно понять сколько каких методов.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            static void CheckInvariants(NodePtr node, std::vector<T>& values,
Плохая тема передавать переменные по ссылке. Надо либо по константной ссылке или легкие по значению, либо по указателю. В первом случае -- это входные переменные, которые не должны меняться и используются как input. Во втором случае -- это выходные переменные, в которые пишется выход. Но тогда пользователю функции надо подсказать в какие переменные ты пишешь. Кроме того, выходные переменные пишутся в конце. Сравни
```cpp
int x = 5;
f(x);
// или
int x = 5;
f(&x);
```
Второй вызов намекает, что x будут менять. А в первом это непонятно. scanf именно этот принцип использует.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        NodePtr GetNearestLeaf(NodePtr node);
Помещай все данные в конце класса, не делай их в перемешку с функциями.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        NodePtr root;
Тут должен быть сырой указатель либо ссылка на дерево. А еще лучше какой-нибудь аналог const_iterator, чтобы не изгадить дерево.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        NodePtr GetNearestLeaf(NodePtr node);
Почему это не функция Node?

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +    template<typename T>
Не выноси имплементацию методов для шаблонов. У тебя слишком много шума получается. Я же про все это писал.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        Node::Unlink(root_);
Вот как ты борешься с циклическими ссылками. Ну это все не понадобится.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +    namespace {
Никогда не используй anonymous namespace в header-файлах.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        bool Find(const T& value, std::shared_ptr<Observable<TreeInfo<T>>> port = nullptr);
Нарушение интерфейса дерева. Его методы ничего не должны знать про какие-то порты.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        void Print(std::ostream& os) const;
Вместо метода print лучше перегрузить оператор operator<<, тогда ты можешь куда угодно сериализовать.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        [[nodiscard]] std::string Str() const;
Что то за метод? Зачем он?

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        [[nodiscard]] std::vector<T> Values() const;
Зачем тот метод?

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +                                    RedBlackTree<T>* tree);
Если ты оставишь только свою структуру Node, то эти методы теряют смысл. Они имеют смысл в контексте дерева, но не одного узла. Я бы вообще в структурах не делал бы никаких методов, а все обслуживающие методы бы делал снаружи, особенно статические. Ибо у тебя нет скрытых данных, потому нет смысла в статических функциях. Ты их просто скрываешь за дополнительным именем, вместо RotateLeft тебе надо писать Node::RotateLeft.
Я бы вынес все методы наружу в дерево. Кроме быть может методов вроде взятия родителей и прочую навигацию. Но даже их можно делать внешними.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        }
Если уж ты сделал FirstNode, то было бы неплохо сделать итераторы и константные итераторы и сделать методы begin и end совместимые с алгоритмами из stl и языком.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            tree_info.node_to_status[node] = DEFAULT;
Сделай это дефолтным значением.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        std::map<NodePtr, Status> node_to_status;
Тут сырые указатели.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +            if (node->GetUncle() && node->GetUncle()->color == Color::RED) {
Когда ты пишешь код вида
```cpp
a->b->c->function()
```
Это считается ошибкой проектирования. Это значит, что объект a не имеет достаточно хороший интерфейс для взаимодействия с ним. Потому я подобный код
```cpp
node->GetUncle()->color
```
предпочитаю менять на
```cpp
Uncle(node)->color
```

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +        while (true) {
while (true) -- признак плохого дизайна и обычно причина разных непредвиденных оптимизаций. Неужели тут нет условия остановки?

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +    enum Color { RED, BLACK };
- Не используй заглавные названия для элементов enum. Такие названия используют только для макросов. Внутри enum-а можно использовать обычные имена. Так будет лучше читаться.
- Используй scoped enum: enum class Color { red, black}; Тогда имена не будут утекать в global namespace.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +                kid = parent->WhichKid(node);
По идее whichKid должно запускаться от node только и иметь три ответа: left, right, non. В любом случае должно быть три значения, если parent не родитель node, то будет non.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +                    (!sibling->right || sibling->right->color == Color::BLACK)) {
Вот что это за условие проверяется?

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.h
> +    bool RedBlackTree<T>::Erase(const T& value, std::shared_ptr<Observable<TreeInfo<T>>> port) {
Что-то охренеть какая длина кода получилась. И условия какие-то дикие в if-ах и логика непроглядывается. Надо что-то с этим делать.

2023-05-15 18:40 UTC, DimaTrushin commented on red_black_tree.cpp
> +    void PrintLines(std::ostream& os, int32_t depth) {
Это еще что такое?

2023-05-15 18:40 UTC, DimaTrushin commented on queries.h
> +        int32_t value;
а почему в application тип ключа int, а тут int32_t? Лучше сделать единообразно.

2023-05-15 18:40 UTC, DimaTrushin commented on controller.h
> +        void SetModel(Model* model);
Я бы устанавливал модель в конструкторе. Чтобы контроллер всегда был к ней привязан.

2023-05-15 18:40 UTC, DimaTrushin commented on controller.h
> +        void OnNotifyFromView(const DataViewController& value);
Это должен быть приватный метод.

2023-05-15 18:40 UTC, DimaTrushin commented on controller.h
> +        ObserverViewControllerPtr observer_view_controller;
Тут должен быть порт, а не указатель на него.

2023-05-15 18:40 UTC, DimaTrushin commented on controller.cpp
> +        if (query.query_type == TreeQueryType::INSERT) {
Сделай switch по enum-у.

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +    struct DrawableNode {
Я еще ожидаю увидеть DrawableTree

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        std::shared_ptr<DrawableNode> right;
unique_ptr и еще raw ptr на родителя.

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        Status status;
А тут статус нужен для отрисовки?

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        void OnNotifyFromModel(const DataModelView& value);
Вот это должен быть приватный метод. И назови по нормальному.

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        void UnsubscribeFromController(ObserverViewControllerPtr observer_view_controller);
Вот этого быть не должно.

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        const float default_node_diameter = 50;
если используешь константы, то делай их static и constexpr.

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        float current_width = 960;
Почему часть константы, а часть нет?

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        QGraphicsScene* main_scene;
- Где у тебя основное Qt окно?
- Кто владеет этими ресурсами?

2023-05-15 18:40 UTC, DimaTrushin commented on view.h
> +        int trees_to_show_counter = 0;
Почему эти параметры здесь после Qt ресурсов? Как они сгруппированы?

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        std::string GetTextAndClear(QLineEdit* button) {
Как это QLineEdit button??

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        main_layout = new QGridLayout;
Вот эти все ресурсы и ниже у тебя текут. Дело в том что в Qt есть понятие владения. Владелец удаляет всех, кем он владеет. Владельца указывают в конструкторе. Выше main_scene у тебя во владении this, поэтому когда view удалится, у тебя удалится и main_scene. А тут у тебя нет владельца у QGridLayout, потому его никто не удаляет. Надо либо делать владельцев, либо в unique_ptr вкладывать.

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        } catch (...) {
От кого ты тут перехватываешь исключения? от std::stoi? Тогда только его и надо погружать в try block. А если не только его, то какого хрена оповещение контроллера может бросить исключение?

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        HideButtons();
Вместо скрытия кнопок лучше деактивировать их. Они будут видимы, но не активны.

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        QTimer::singleShot(trees_to_show_counter * 500, this, [=]() {
Волшебная константа 500.

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        QTimer::singleShot(trees_to_show_counter * 500, this, [=]() {
Плохая тема. У тебя не блокирующие вызовы. И эта схема не поддерживает прилет команд от двух источников пока анимация не закончится. Идея неблокирующей отрисовки -- хороша, но имплементация очень плохая.

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        result->x = static_cast<float>(counter) * (horizontal_space_between_nodes + default_node_diameter);
какого хрена у тебя тут делает cast? Это ошибка дизайна.

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +                DrawableNode{0, 0, 0, BLACK, static_cast<Status>(0), nullptr, nullptr});
Какого хрена каст к enum-у?

2023-05-15 18:40 UTC, DimaTrushin commented on view.cpp
> +        current_width = static_cast<float>(size().width() - 100);
Волшебная константа.

2023-05-15 18:40 UTC, DimaTrushin commented on tests/test_correctness.cpp
> +            for (int node = 1; node <= 1000; ++node) {
Я бы добавил проверку рекурсивную всех инвариантов дерева от корня.

2023-05-15 18:40 UTC, DimaTrushin commented on tests/test_performance.cpp
> +            auto finish = std::chrono::high_resolution_clock::now();
Посмотри вот тут
https://stackoverflow.com/questions/879408/c-function-wrapper-that-behaves-just-like-the-function-itself
ответ от Мыколы Голубева как надо правильно замерять производительность методов.

2023-05-21 22:53 UTC, gmusya commented on view.cpp
> +        QTimer::singleShot(trees_to_show_counter * 500, this, [=]() {
Что-то я так и не обнаружил, как это сделать. Если использовать QThread::sleep, то просто многократно происходит задержка, а затем разом все отрисовывается (и виден только начальный вариант, а после него только конечный)

2023-05-21 22:56 UTC, gmusya commented on view.cpp
> +        result->x = static_cast<float>(counter) * (horizontal_space_between_nodes + default_node_diameter);
Рисовать хотелось бы в вещественных координатах (метод addEllipse позволяет например), но при этом координаты зависят от номера вершины (и еще от текущих размеров окна, являющихся целым числом). Как от этого возможно избавиться?

2023-05-21 22:58 UTC, gmusya commented on view.h
> +        QGraphicsScene* main_scene;
Добавил окно. Я верно понимаю, что в окне я буквально только храню ресурсы (ну и всякие методы в духе "активируй/деактивируй кнопки" туда, а всё логика по рисованию должна находиться во View?)

2023-05-21 22:59 UTC, gmusya commented on view.h
> +        float current_width = 960;
current_width не константа, чтобы при изменении пользователем размера экрана, подбирать радиусы для нод

2023-05-21 23:03 UTC, gmusya commented on red_black_tree.h
> +            NodePtr GetUncle();
Так это же не геттеры, а вычисления каких-то товарищей в дереве, чтобы не писать node->parent->parent

2023-06-09 12:44 UTC, DimaTrushin approved these changes

2023-06-09 12:45 UTC, merged